### ISSUE TITLE
Use Template literals

### ISSUE THREAD

**Issue by gr8fuljoe5** [rbrisita/python-examples#1]
https://github.com/rbrisita/fakeFourSquare/blob/ec0e41d3fa7ea9a2611d298c2e1a1f42924740a5/app/static/js/app.js#L5

By far, my favorite feature of ES6 is template literals. It allows you to easily manage your templates and you don't have to do a `replace` method to append your data. 

EX:
```

const dataSource = {
   name: "Bobby Window",
   occupation: "Ladies Man",
   age: "None of your business!" 
}
const {name, occupation, age} = dataSource;
const example_tpl = `
   <div>
      <span>${name}</span>
      <span>${occupation}</span>
      <span>${age}</span>
  </div>
`

```

**Comment by rbrisita** [comment]
Yes, I saw that and thanks for bringing it up with the comical example. 😜 It will be exercised in the other demos that will use frameworks that need to be transpiled; Angular and TypeScript for example.
