### ISSUE TITLE
Avoid putting variables in the global scope

### ISSUE THREAD

**Issue by gr8fuljoe5** [rbrisita/python-examples#2]
https://github.com/rbrisita/fakeFourSquare/blob/ec0e41d3fa7ea9a2611d298c2e1a1f42924740a5/app/static/js/app.js#L68

So its just best practice to not do this. It's perfectly fine if you're the only person working on the app and you have complete control, but in general it's a bad habit.

**Comment by rbrisita** [comment]
For sure, since all the application code is located in one file, it was the trade off between the 'one pager' or slightly increasing complexity and management. On the JS side, the goal was usage of jQuery and other libraries which I believe is fine.
