### ISSUE TITLE
Use "then" method for this logic

### ISSUE THREAD

**Issue by gr8fuljoe5** [rbrisita/python-examples#3]
https://github.com/rbrisita/fakeFourSquare/blob/ec0e41d3fa7ea9a2611d298c2e1a1f42924740a5/app/static/js/app.js#L139

I haven't used jQuery in a while, but I recall there being a `.then()` method which automatically resolves a promise

```
$.get('some_uri_.json').then((data) => {
// response logic goes here

return somedata;
}).done((data) => {
 // your data is ready to be binded to the DOM and the promise has been resolved. 
})
```

NOTE: Syntax might be a little off, but that's the basic concept

**Comment by rbrisita** [comment]
You can and I would lean towards using that approach (when, then) if there were a series of calls. 'done' is a promise resolver (successful) just with a different function signature. I would agree that moving the anonymous function into a chained 'done' function would be more readable to someone unfamiliar with jQuery ajax request signature.
